### ISSUE TITLE
Add line highlight for folders in tree-view

### ISSUE THREAD

**Issue by emil14** [cdonohue/pristine-ui#11]
I just switched from the Atom's "One-Dark" UI-theme to this and it's great, but I lack the backlighting of the focused folder, as in the "One-Dark". 

The problem is especially relevant with respect to the folders marked with git. It is impossible to understand which folder is highlighted:

![screenshot from 2017-07-10 16-23-06](https://user-images.githubusercontent.com/6453537/28020270-61c682b6-658c-11e7-9a5b-0696604fd9c9.png)

Can you return a behavior similar to "One-Dark"? Or maybe add an option for that. Thanks.

**Comment by cdonohue** [comment]
@emil14 thanks for the suggestion. I've just released a new version, `1.1.0` that should have this change in it.

**Comment by emil14** [comment]
thanks! it works
