### ISSUE TITLE
Thoughts on removing border-bottom from .title-bar

### ISSUE THREAD

**Issue by bensk** [cdonohue/pristine-ui#13]
Looks much cleaner, in my opinion, when tabs blend into the custom titlebar. 

Before: 

<img width="392" alt="before" src="https://user-images.githubusercontent.com/7450756/28500456-b1de2380-6f96-11e7-8b3e-d18eb5385d4e.png">

After:

<img width="396" alt="after" src="https://user-images.githubusercontent.com/7450756/28500457-b4a7cd1e-6f96-11e7-9b33-832b008cb0cf.png">

Thanks!

**Comment by cdonohue** [comment]
I'm in agreement @bensk! I'll get the change made later today. Thanks for the suggestion.

**Comment by bensk** [comment]
Thank you! Far and away my favorite UI for Atom.

**Comment by cdonohue** [comment]
@bensk How about something like this? I've removed the border and added some breathing room between the title bar and the tabs, while also rounding the corners of the active tab to let it stand on its own.

<img width="556" alt="screen shot 2017-07-24 at 9 39 07 am" src="https://user-images.githubusercontent.com/1928846/28528745-3831bf4c-7054-11e7-899e-4b40ef1146ee.png">

**Comment by bensk** [comment]
Love it!

**Comment by cdonohue** [comment]
@bensk the change is out in the wild! Thanks again for discussing this 😄 .
