### ISSUE TITLE
Tab bar too tall?

### ISSUE THREAD

**Issue by danqing** [cdonohue/pristine-ui#14]
Thanks for this cool theme :)

It seems that a recent version made the tabs a lot taller. Is this intended or bug? I'd much prefer the original - at least it'd be great if this can be optional.

Also the text doesn't seem to be vertically aligned in the tabs (too low).

**Comment by cdonohue** [comment]
I did push an update and modified the tab size, @danqing. Maybe this could be a setting for the theme and users can select if they want compact or more spacious tabs?

**Comment by danqing** [comment]
Yes, that'd be very welcomed :) I personally would love to stay with the old height.

Btw unrelated, the Choose a Theme page can use a bit more work :) The gear button can have a bit more padding left and the dropdown seems a little taller.

Thanks again for this great theme!

**Comment by cdonohue** [comment]
On second thought @danqing, I might just shrink the tabs a bit while also removing some padding. I'll post up some images here with the results. Also, thanks for the catch on the `theme settings` view!

**Comment by cdonohue** [comment]
I feel like these changes make the tabs a bit more compact, while also retaining a height that is larger than the original design.

<img width="506" alt="screen shot 2017-07-25 at 2 49 04 pm" src="https://user-images.githubusercontent.com/1928846/28590630-73766acc-7148-11e7-969b-6b44e42f437c.png">

**Comment by danqing** [comment]
That looks nice :)

**Comment by cdonohue** [comment]
@danqing I'll also roll your theme settings fixes into this next patch update as well. Thanks again!

<img width="535" alt="screen shot 2017-07-25 at 3 01 44 pm" src="https://user-images.githubusercontent.com/1928846/28591152-461ec162-714a-11e7-8919-a43a593d0369.png">

**Comment by cdonohue** [comment]
@danqing these changes are live now
