### ISSUE TITLE
Button: Wrong vertical alignment of icon

### ISSUE THREAD

**Issue by pfitzseb** [cdonohue/pristine-ui#15]
![screenshot_20170801_115507](https://user-images.githubusercontent.com/6735977/28820001-46b93d26-76b0-11e7-8a2b-0143a42cd4f5.png)

Getting rid of the `vertical-alignment: top` kinda fixes it, but I'm not sure if that doesn't break anything else.

**Comment by cdonohue** [comment]
Interesting, @pfitzseb, I wonder if another package is conflicting with the styles, here is a screenshot of mine:
<img width="330" alt="screen shot 2017-08-02 at 2 28 18 pm" src="https://user-images.githubusercontent.com/1928846/28891096-f237d21e-778e-11e7-8f12-c01f182a0009.png">

**Comment by cdonohue** [comment]
@pfitzseb can you do me a favor? Can you inspect the icon styles and open the style inspector (`Cmd`+`option`+`I`)? If you can, please post your findings.

**Comment by pfitzseb** [comment]
Interestingly enough this is reproducible with `atom --safe`:
![image](https://user-images.githubusercontent.com/6735977/28915260-d7cc20fa-783e-11e7-87d1-6b7d23834231.png)
Not sure what is going on there, but it definitely can't be pristine-ui's fault. 

Sorry for the noise, and thanks for the great theme! :)

**Comment by cdonohue** [comment]
Interesting find @pfitzseb. Thanks for the research.
