### ISSUE TITLE
Tab-About Page Background Color Mismatch

### ISSUE THREAD

**Issue by keplersj** [cdonohue/pristine-ui#16]
<img width="965" alt="screen shot 2017-08-08 at 5 37 12 pm" src="https://user-images.githubusercontent.com/594124/29099106-6176a102-7c60-11e7-841d-4a6033ef0ab6.png">

Found this one while updating to Atom 1.19 today

**Comment by cdonohue** [comment]
What `syntax` theme are you using @keplersj ?

**Comment by keplersj** [comment]
[one-dark-vivid](https://atom.io/packages/one-dark-vivid-syntax). I should file an issue there, shouldn't I?

**Comment by cdonohue** [comment]
@keplersj let me check locally. I'll try and debug with that theme. The ui colors are derived from the user's syntax theme, so maybe this is an outlier?  I'll post up here if I find something.

**Comment by cdonohue** [comment]
@keplersj I have an update out that should fix this. I tested with your `one-dark-vivid` example (great syntax theme btw).

**Comment by keplersj** [comment]
Looks great! Thanks!
