### ISSUE TITLE
Wrong banner color?

### ISSUE THREAD

**Issue by danqing** [cdonohue/pristine-ui#18]
![screen shot 2017-09-08 at 10 11 48 pm](https://user-images.githubusercontent.com/5134133/30237249-cf26fcb6-94e2-11e7-824f-ea4cb16aafc1.png)

I'm not sure if this is part of the ui theme, but the banner should have a green color.

**Comment by cdonohue** [comment]
Hmmm, that's interesting @danqing. Can you provide steps to recreate that behavior?

**Comment by danqing** [comment]
You need to have some packages with the red bug icon in the status bar. Then if you click on it and choose "rebuild package", you will see this banner.

**Comment by cdonohue** [comment]
What was the package in question @danqing ? I'm attempting to reproduce and see what's going on. Can you give me the name of a package that would give me a bug in the status bar?

That might take considerably less time than me randomly downloading packages 😄

**Comment by danqing** [comment]
The one I downloaded is go-debug :)

**Comment by cdonohue** [comment]
Thanks again for finding this @danqing. I've updated the code so these alerts appear as they should.
