### ISSUE TITLE
more contrast for focus tab

### ISSUE THREAD

**Issue by t7yang** [cdonohue/pristine-ui#2]
its not clear that which tab is focus in tab bar, so you can make it more contrast.

genesis-ui's distraction free is a pretty good example for imitate :-)

**Comment by cdonohue** [comment]
@t7yang, are you referring to the tree view (on the left)? Would you mind posting a screenshot for reference?

**Comment by t7yang** [comment]
the tab bar, actually. below the screen shot from Genesis (fore) and the Pristine (back).
the Genesis UI make more easier to distinguish between the active tab and inactive tab, whereas Pristine is more harder even with the indicator (its become worse if you open a lot of tab).
![2016-11-16_223120](https://cloud.githubusercontent.com/assets/4502661/20351857/d3e6d554-ac4f-11e6-9b7b-66b42239ecc2.jpg)

**Comment by cdonohue** [comment]
The `background-color` of the active tab in `pristine-ui` is based on the background of your syntax theme, @t7yang.

See the following two examples:

##### Using `duotone-dark-syntax`

![screenshot 2016-11-16 13 01 28](https://cloud.githubusercontent.com/assets/1928846/20361431/25b6d6ac-abfd-11e6-901c-bb911abfc136.png)

##### Using `duotone-light-syntax`

![screenshot 2016-11-16 13 01 01](https://cloud.githubusercontent.com/assets/1928846/20361444/2df2a1d4-abfd-11e6-9153-1440bbd46527.png)

I'm curious, what syntax theme are you using currently?

**Comment by t7yang** [comment]
one-dark-material-syntax 😄 
OK, now i know, thx.

try switching among duotone-dark-syntax, one-dark and one-dark-material, still having the some problem...
