### ISSUE TITLE
Code background issue

### ISSUE THREAD

**Issue by danqing** [cdonohue/pristine-ui#20]
<img width="463" alt="screen shot 2017-09-13 at 11 32 02 am" src="https://user-images.githubusercontent.com/5134133/30394495-18e28026-9878-11e7-844e-d4f092acdc3a.png">

The code in the black box (pre?) should not have its own background.

**Comment by cdonohue** [comment]
@danqing can you provide steps to recreate the above scenario?

**Comment by danqing** [comment]
Hmm yeah sorta.. With Atom Beta, install atom-ide-ui and ide-python, and it might come up.

I think it's just `background-color` being applied to `code`, but should be removed when it's in a well.

**Comment by cdonohue** [comment]
@danqing this should be fixed in `1.1.9`
