### ISSUE TITLE
Icons not updated

### ISSUE THREAD

**Issue by udayms** [cdonohue/pristine-ui#21]
Hi... I have this weird issue that my icons are not updated after setting pristine-ui as the theme. Anyone else face this issue?
![screen shot 2017-09-14 at 11 33 35 am](https://user-images.githubusercontent.com/186861/30447357-b281d8c6-9940-11e7-8df8-e31326605659.png)

**Comment by cdonohue** [comment]
What icon package are you using @udayms ?

**Comment by udayms** [comment]
That solved my problem... I checked for the icon packages in installed packages and found that i had file-icons and seti-icons installed. when I removed seti-icons, my problem went away....
