### ISSUE TITLE
Atom issues palette is oversizing the coding area

### ISSUE THREAD

**Issue by ghost** [cdonohue/pristine-ui#3]
After chose Pristine as my UI Theme and open a file that has a lots of Rubocop's warnings, Atom's issue palette with these warnings is oversizing the coding area.

Expected result: When a lot of issues are listed on Atom's issue palette, it must display a scrolling bar.
Actual result:   When a lot of issues are listed on Atom's issue palette, no scrolling bar is displayed.

Ruby
Rails
Rubocop
Atom 1.12.2
Prestine 1.0.6

See the screenshot for more details.

![captura de tela 2016-11-16 as 12 33 03](https://cloud.githubusercontent.com/assets/17497134/20351533/59665d54-abfa-11e6-908c-63d94176da9f.png)

**Comment by cdonohue** [comment]
Thanks for catching this @thiagopecanha. I'll get a fix out today for this!

**Comment by cdonohue** [comment]
@thiagopecanha this should be resolved now in `v1.0.7`

**Comment by ghost** [comment]
@cdonohue , working as expected, awesome.

Thank you very much.
