### ISSUE TITLE
Seti Icons are displaced.

### ISSUE THREAD

**Issue by felstormrage** [cdonohue/pristine-ui#7]
In the latest update seti-icons update icons everywhere are shifted either up or down. I've tried all possible settings for pristine. Still no luck. 
![screenshot_20170602_023729](https://cloud.githubusercontent.com/assets/14135943/26700843/8a4b5f04-473c-11e7-9c36-84e08096dabc.png)
![screenshot_20170602_023744](https://cloud.githubusercontent.com/assets/14135943/26700842/8a4b432a-473c-11e7-9e9e-27456cec1c51.png)

**Comment by cdonohue** [comment]
I'll look into this @rednithin, thanks for sharing

**Comment by cdonohue** [comment]
@rednithin This has to do with the `seti-icons` package making modifications for specific ui themes 
> https://github.com/wyze/atom-seti-icons/blob/master/styles/theme-overrides.less

To keep things consistent, I would suggest submitting a PR in that repo to whitelist `pristine-ui`.
