### ISSUE TITLE
New Syntax theme removes Tab and Scroll wheel colors.

### ISSUE THREAD

**Issue by SoraKatadzuma** [cdonohue/pristine-ui#8]
I have been trying to make a new syntax them for atom under your UI theme. And for some reason the tabs and scroll wheel lose their color. I can't even seem to override the situation. Can you enlighten me on how to fix this issue? It doesn't happen with built in syntax's just ones that I create.

**Comment by cdonohue** [comment]
@SoraKatadzuma try to replicate this again. I just updated `pristine-ui` to fix some issues with new Atom changes. Let me know how I can help.
