### ISSUE TITLE
Text in status bar in "windows" is too small

### ISSUE THREAD

**Issue by notbadri** [cdonohue/pristine-ui#9]
The text in the status bar is too small to read. It is not inline with the other elements of the UI. 
P.S. Love the spacious mode in this UI

**Comment by cdonohue** [comment]
Thanks for posting @badri-n18 . This theme is about to go through a revamp based on some of the new UI changes in Atom. So, I'll make sure this gets addressed.

**Comment by cdonohue** [comment]
With that being said, would you mind posting a screenshot just to clarify?

**Comment by cdonohue** [comment]
@badri-n18 this should be resolved with the latest version, `1.1.0`. Please let me know.

**Comment by notbadri** [comment]
thank you very much. works flawlessly now :)
